[colors]
background = '#1c1b1a'
foreground = '#cecdc3'
selection-background = '#cecdc3'
selection-foreground = '#4385be'
cursor = '#cecdc3'
black = '#1c1b1a'
red = '#d14d41'
green = '#879a39'
yellow = '#d0a215'
blue = '#4385be'
magenta = '#ce5d97'
cyan = '#3aa99f'
white = '#b7b5ac'
light_black = '#575653'
light_red = '#d14d41'
light_green = '#879a39'
light_yellow = '#d0a215'
light_blue = '#4385be'
light_magenta = '#ce5d97'
light_cyan = '#3aa99f'
light_white = '#cecdc3'
