[colors]
background = '#fffcf0'
foreground = '#100f0f'
selection-background = '#cecdc3'
selection-foreground = '#100f0f'
cursor = '#100f0f'
black = '#100f0f'
red = '#af3029'
green = '#66800b'
yellow = '#ad8301'
blue = '#205ea6'
magenta = '#a02f6f'
cyan = '#24837b'
white = '#f2f0e5'
light_black = '#575653'
light_red = '#d14d41'
light_green = '#879a39'
light_yellow = '#d0a215'
light_blue = '#4385be'
light_magenta = '#ce5d97'
light_cyan = '#3aa99f'
light_white = '#fffcf0'
