add_newline = false

# format = '''
# [┌](bold grey)$fill
# [│](bold grey) \[$time\] $username[@](green)$hostname$directory$all
# [└─>](bold grey)$character 
# '''
format = '[\[$username@$hostname:$directory\]](bold #FFB26F) $all'

# reduce command timeout for larger repos and directories
command_timeout	= 100

[fill]
symbol = '─'
style = 'bold grey'

[character]
disabled = true
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[line_break]
disabled = true

[cmd_duration]
format = 'took [$duration](yellow)'
disabled = true

[directory]
# truncation_length = 3
truncation_length = 100
# truncation_symbol = '…/'
truncate_to_repo = false
# format = ' in [$path]($style)[$read_only]($read_only_style) '
format = '[$path](bold #FFB26F)'

[package]
disabled = true

[ocaml]
# format = 'via [$symbol($version )]($style)'
local_switch_indicator = '.'

[golang]
format = 'via [$symbol($version )](bold blue)'

[username]
# format = "[$user@](green)"
# format = "[fede](green)"
format = "$user"
show_always = true
# disabled = true

[hostname]
ssh_only = false
format = "$hostname"
# format = "[$hostname](green)"
# disabled = true

[time]
format = '[$time](yellow)'
time_format = '%H:%M'
disabled = true
